Manager:
  experiment_name: Exp9
  save_point: /home/clement/Documents/Lucas/RetinalSurgeryRecognition/runs/
  #save_point: C:\Users\lucas\OneDrive\Documents\Professionnel\StageMontreal2020\Python\RetinalSurgeryRecognition/RecurrentNetwork\runs\
  gpu: 0 #à modifier selon le nombre de GPU
  seed: 1234

Dataset:
  img_size: 224
  batch_size: 8 #DOIT ETRE MISE à 1 POUR LA COLLECTE DES FEATURES VIA LE CNN (pour l'utilisation du RNN)
  groundtruth_path: '/home/clement/CATARACTS/GroundTruth/'
  #img_folder: '/home/clement/CATARACTS/Testing_Data/'
  img_folder: '/home/clement/Documents/Lucas/RetinalSurgeryRecognition/RecurrentNetwork/CNN_features_2/Training_Data/'
  #groundtruth_path: 'C:\Users\lucas\OneDrive\Documents\Professionnel\StageMontreal2020\Python\GroundTruth\'
  #img_folder: 'C:\Users\lucas\OneDrive\Documents\Professionnel\StageMontreal2020\Python\Training_Data\'
  #img_folder: 'C:\Users\lucas\OneDrive\Documents\Professionnel\StageMontreal2020\Python\CNN_features\'
  load_recursirvely: True
  validation_ratio: 0.2  # From the training size
  num_workers: 8  # Workers used for parallel data loading MODIFIED, WAS 8
  pin_memory: True  # Place loaded data in the CPU to GPU buffer.
  path_weights: /home/clement/Documents/Lucas/RetinalSurgeryRecognition/runs/weights/
  rnn_sequence: 100

Validation:
  validation_step: 500
  max_batch_validation: 4

Training:
  nb_epochs: 3
  loss_type: CE
  lr: 0.1
  b1: 0.9
  b2: 0.99
  weight_decay: 0
  save_iteration: 20000
  weighted_loss: True
  train_flag: True
  

Testing:
  log_file: test_results.log
  eval_performance: True
  batch_size: 1
  img_folder: '/home/clement/Documents/Lucas/RetinalSurgeryRecognition/RecurrentNetwork/CNN_features_2/Testing_Data/'
  #img_folder: 'C:\Users\lucas\OneDrive\Documents\Professionnel\StageMontreal2020\Python\CNN_features\'

CNN:
  pretrained: True # Pretrained version
  model: resnet
  # The following variable is path to an already trained model set of weights. If set,
  # it will override the reading of the a pretrained network (above option).
  # An empty string disables the option.
  # eg: trained_model_path: ../../runs/CityScape-Perspective/trained_model/
  #Inception Unweighted
  #trained_model_path: /home/clement/Documents/Lucas/RetinalSurgeryRecognition/runs/Exp1/trained_model/trained_model_iter_42500_loss_2.2453.pth
  #Inception weighted
  #trained_model_path: /home/clement/Documents/Lucas/RetinalSurgeryRecognition/runs/Exp2/trained_model/trained_model_iter_48500_loss_2.5815.pth
  #resnet
  #trained_model_path: /home/clement/Documents/Lucas/RetinalSurgeryRecognition/runs/Exp3/trained_model/trained_model_iter_51500_loss_2.1597.pth
  #resnet weighted
  #trained_model_path: /home/clement/Documents/Lucas/RetinalSurgeryRecognition/runs/RNN/Exp1/trained_model/trained_model_iter_45000_loss_2.2325.pth
  #LSTM1
  #trained_model_path: /home/clement/Documents/Lucas/RetinalSurgeryRecognition/RecurrentNetwork/runs/Exp5_LSTM/trained_model/trained_model_iter_9000_loss_2.8498.pth
  
  #MON MODEL, POUR TESTS
  #trained_model_path: C:\Users\lucas\OneDrive\Documents\Professionnel\StageMontreal2020\Python\runs\PhaseRecognition\Exp2\trained_model\trained_model_iter_10_loss_2.9062.pth
  n_classes: 19
  continue_training: True # If False, only the last FCN layers are trained (the rest of the network being fixed).

