##EXP4 = RESNET, 18 classes -9 -12
##EXP5 = RESNET, 18 classes -9 -12 -0
##EXP6 = RESNET, 18 classes -9 -12, weights
##EXP7 = RESNET, 18 classes -9 -12 -0, weights
##EXP8 = RESNET, 18 classes -9 -12, training only last layers
##EXP9 = RESNET + LSTM, 18 classes -9 -12

Manager:
  experiment_name: Exp7
  save_point: /home/clement/Documents/Lucas/RetinalSurgeryRecognition/runs/
  gpu: 0 #à modifier selon le nombre de GPU
  seed: 1234
  
  ##code test for debug
  #save_point: C:\Users\lucas\OneDrive\Documents\Professionnel\StageMontreal2020\Python\runs\

Dataset:
  #img_size: 299 #Inception
  img_size: 224 #Resnet
  batch_size: 8
  groundtruth_path: '/home/clement/CATARACTS/GroundTruth/'
  #img_folder: '/home/clement/CATARACTS/Training_Data/'
  img_folder: '/home/clement/CATARACTS/Training_zero/' #class 0 removed
  
  ##code test for debug
  #groundtruth_path: 'C:\Users\lucas\OneDrive\Documents\Professionnel\StageMontreal2020\Python\GroundTruth\'
  #img_folder: 'C:\Users\lucas\OneDrive\Documents\Professionnel\StageMontreal2020\Python\Training_Data\'
  load_recursirvely: True
  validation_ratio: 0.2  # From the training size
  num_workers: 8  # Workers used for parallel data loading
  pin_memory: True  # Place loaded data in the CPU to GPU buffer.
  path_weights: /home/clement/Documents/Lucas/RetinalSurgeryRecognition/runs/weights/



Validation:
  validation_step: 500
  max_batch_validation: 4

Training:
  nb_epochs: 2
  loss_type: CE+dice
  lr: 0.001
  b1: 0.9
  b2: 0.99
  weight_decay: 0
  save_iteration: 20000
  weighted_loss: True
  train_flag: True

Testing:
  log_file: test_results.log
  save_prediction: True
  eval_performance: True
  batch_size: 1
  #img_folder: '/home/clement/CATARACTS/Testing_Data/'
  img_folder: '/home/clement/CATARACTS/Testing_zero/' #class 0 removed
  
  #img_folder: 'C:\Users\lucas\OneDrive\Documents\Professionnel\StageMontreal2020\Python\Testing_Data\'

    
CNN:
  pretrained: True
  model: resnet

  ##Exp4
  #trained_model_path: /home/clement/Documents/Lucas/RetinalSurgeryRecognition/runs/Exp4/trained_model/trained_model_iter_156000_loss_2.0457.pth
  
  ##Exp5
  #trained_model_path: /home/clement/Documents/Lucas/RetinalSurgeryRecognition/runs/Exp5/trained_model/trained_model_iter_82000_loss_2.0386.pth
  
  ##Exp6
  #trained_model_path: /home/clement/Documents/Lucas/RetinalSurgeryRecognition/runs/Exp6/trained_model/trained_model_iter_123000_loss_2.0534.pth

  ##Exp7
  trained_model_path: /home/clement/Documents/Lucas/RetinalSurgeryRecognition/runs/Exp7/trained_model/trained_model_iter_45000_loss_2.0601.pth
  
  ##Exp8
  #trained_model_path: /home/clement/Documents/Lucas/RetinalSurgeryRecognition/runs/Exp8/trained_model/trained_model_iter_63000_loss_2.2657.pth

  ##code test for debug
  #trained_model_path: C:\Users\lucas\OneDrive\Documents\Professionnel\StageMontreal2020\Python\runs\PhaseRecognition\Exp1\trained_model\trained_model_iter_0_loss_2.9618.pth
  
  n_classes: 19
  continue_training: False # If False, only the last FCN layers are trained (the rest of the network being fixed).

