Manager:
  experiment_name: Exp1
  save_point: /home/clement/Documents/Lucas/RetinalSurgeryRecognition/runs/
  #save_point: C:\Users\lucas\OneDrive\Documents\Professionnel\StageMontreal2020\Python\runs\
  gpu: 0 #à modifier selon le nombre de GPU
  seed: 1234

Dataset:
  img_size: 512
  batch_size: 8 #was 16
  groundtruth_path: '/home/clement/CATARACTS/GroundTruth/'
  img_folder: '/home/clement/CATARACTS/Training_Data/'
  #groundtruth_path: 'C:\Users\lucas\OneDrive\Documents\Professionnel\StageMontreal2020\Python\GroundTruth\'
  #img_folder: 'C:\Users\lucas\OneDrive\Documents\Professionnel\StageMontreal2020\Python\Training_Data\'
  load_recursirvely: True
  validation_ratio: 0.2  # From the training size
  num_workers: 8  # Workers used for parallel data loading MODIFIED, WAS 8
  pin_memory: True  # Place loaded data in the CPU to GPU buffer.
  path_weights: /home/clement/Documents/Lucas/RetinalSurgeryRecognition/runs/weights/
  #path_weights: C:\Users\lucas\OneDrive\Documents\Professionnel\StageMontreal2020\Python\runs\weights\



Validation:
  validation_step: 500
  max_batch_validation: 4

Training:
  nb_epochs: 2
  loss_type: CE+dice
  lr: 0.001
  b1: 0.9
  b2: 0.99
  weight_decay: 0
  save_iteration: 20000
  weighted_loss: True
  train_flag: True

Testing:
  log_file: test_results.log
  save_prediction: True
  eval_performance: True
  batch_size: 8
  img_folder: '/home/clement/CATARACTS/Testing_Data/'

CNN:
  pretrained: True # Pretrained version
  model: inception
  # The following variable is path to an already trained model set of weights. If set,
  # it will override the reading of the a pretrained network (above option).
  # An empty string disables the option.
  # eg: trained_model_path: ../../runs/CityScape-Perspective/trained_model/
  trained_model_path: /home/clement/Documents/Lucas/RetinalSurgeryRecognition/runs/Exp1/trained_model/trained_model_iter_88000_loss_2.0745.pth
  n_classes: 19
  continue_training: True # If False, only the last FCN layers are trained (the rest of the network being fixed).

